import Vue from 'vue';
import MSelector from '@/components/MSelector';
import MRadio from '@/components/MRadio';
import MView from '@/components/MView';
import MRemark from '@/components/MRemark';
import MFormEdit from '@/components/MFormEdit';
import MFormItem from '@/components/MFormItem';
import MDialog from '@/components/MDialog';
import MEdit from '@/components/MEdit';
import MEditHint from '@/components/MEditHint';
import SaveButton from '@/components/SaveButton';
import StateFilter from '@/components/StateFilter';
import DatetimeFilter from '@/components/DatetimeFilter';
import MUploader from '@/components/MUploader';
import MPreviewer from '@/components/MPreviewer';
import MAddressView from '@/components/MAddressView';
import MAddressForm from '@/components/MAddressForm';
import SimpleTable from '@/components/SimpleTable';
import Pagination from '@/components/Pagination';
import PageTitle from '@/components/PageTitle';
import QueryButton from '@/components/QueryButton';

Vue.component(MSelector.name, MSelector);
Vue.component(MRadio.name, MRadio);
Vue.component(MView.name, MView);
Vue.component(MRemark.name, MRemark);
Vue.component(MFormEdit.name, MFormEdit);
Vue.component(MFormItem.name, MFormItem);
Vue.component(MEdit.name, MEdit);
Vue.component(MEditHint.name, MEditHint);
Vue.component(SaveButton.name, SaveButton);
Vue.component(MDialog.name, MDialog);
Vue.component(StateFilter.name, StateFilter);
Vue.component(DatetimeFilter.name, DatetimeFilter);
Vue.component(MUploader.name, MUploader);
Vue.component(MPreviewer.name, MPreviewer);
Vue.component(MAddressView.name, MAddressView);
Vue.component(MAddressForm.name, MAddressForm);
Vue.component(Pagination.name, Pagination);
Vue.component(SimpleTable.name, SimpleTable);
Vue.component(PageTitle.name, PageTitle);
Vue.component(QueryButton.name, QueryButton);
