import Vue from 'vue';
import MSelector from '@/components/MSelector';
import MRadio from '@/components/MRadio';
import MView from '@/components/MView';
import MRemark from '@/components/MRemark';
import MViewDialog from '@/components/MViewDialog';
import MFormEdit from '@/components/MFormEdit';
import MFormItem from '@/components/MFormItem';
import MViewItem from '@/components/MViewItem';
import MDialog from '@/components/MDialog';
import MDrawer from '@/components/MDrawer';
import ColFormItem from '@/components/ColFormItem.vue';
import MEdit from '@/components/MEdit';
import MEditHint from '@/components/MEditHint';
import SaveButton from '@/components/SaveButton.vue';
import StateFilter from '@/components/StateFilter.vue';
import DatetimeFilter from '@/components/DatetimeFilter.vue';
import MCollapseItem from '@/components/MCollapseItem';
import MUploader from '@/components/MUploader';
import MPreviewer from '@/components/MPreviewer';
import MAddressView from '@/components/MAddressView';
import MAddressForm from '@/components/MAddressForm';
import MCommonSelect from '@/components/MCommonSelect';
import MPortrait from '@/components/MPortrait';
import FlexItem from '@/components/FlexItem';
import SimpleTable from '@/components/SimpleTable';
import Pagination from '@/components/Pagination';
import PageTitle from '@/components/PageTitle/index.vue';
import QueryButton from '@/components/QueryButton';

Vue.component(MSelector.name, MSelector);
Vue.component(MRadio.name, MRadio);
Vue.component(MView.name, MView);
Vue.component(MRemark.name, MRemark);
Vue.component(MViewDialog.name, MViewDialog);
Vue.component(MFormEdit.name, MFormEdit);
Vue.component(MFormItem.name, MFormItem);
Vue.component(MViewItem.name, MViewItem);
Vue.component(MEdit.name, MEdit);
Vue.component(MEditHint.name, MEditHint);
Vue.component(ColFormItem.name, ColFormItem);
Vue.component(SaveButton.name, SaveButton);
Vue.component(MDialog.name, MDialog);
Vue.component(MDrawer.name, MDrawer);
Vue.component(StateFilter.name, StateFilter);
Vue.component(DatetimeFilter.name, DatetimeFilter);
Vue.component(MCollapseItem.name, MCollapseItem);
Vue.component(MUploader.name, MUploader);
Vue.component(MPreviewer.name, MPreviewer);
Vue.component(MAddressView.name, MAddressView);
Vue.component(MAddressForm.name, MAddressForm);
Vue.component(MCommonSelect.name, MCommonSelect);
Vue.component(MPortrait.name, MPortrait);
Vue.component(FlexItem.name, FlexItem);
Vue.component(Pagination.name, Pagination);
Vue.component(SimpleTable.name, SimpleTable);
Vue.component(PageTitle.name, PageTitle);
Vue.component(QueryButton.name, QueryButton);
