import Vue from 'vue';
import MSelector from './MSelector';
import MRadio from './MRadio';
import MView from './MView';
import MRemark from './MRemark';
import MViewDialog from './MViewDialog';
import MFormEdit from './MFormEdit';
import MFormItem from './MFormItem';
import MViewItem from './MViewItem';
import MDialog from './MDialog';
import MDrawer from './MDrawer';
import ColFormItem from './ColFormItem.vue';
import MEdit from './MEdit';
import MEditHint from './MEditHint';
import CodeEditor from './CodeEditor/index.vue';
import JsonEditor from './JsonEditor/index2.vue';
import SaveButton from './SaveButton.vue';
import StateFilter from './StateFilter.vue';
import DatetimeFilter from './DatetimeFilter.vue';
import MCollapseItem from './MCollapseItem';
import MUploader from './MUploader';
import MPreviewer from './MPreviewer';
import MAddressView from './MAddressView';
import MAddressForm from './MAddressForm';
import MCommonSelect from './MCommonSelect';
import MAttachName from './MAttachName';
import MPortrait from './MPortrait';
import TreeChart from './TreeChart';
import TreeChartEmployee from './TreeChartEmployee';
import FlexItem from './FlexItem';
import SimpleTable from '@/components/SimpleTable';
import Pagination from '@/components/Pagination';
import PageTitle from './PageTitle/index.vue';

Vue.component(MSelector.name, MSelector);
Vue.component(MRadio.name, MRadio);
Vue.component(MView.name, MView);
Vue.component(MRemark.name, MRemark);
Vue.component(MViewDialog.name, MViewDialog);
Vue.component(MFormEdit.name, MFormEdit);
Vue.component(MFormItem.name, MFormItem);
Vue.component(MViewItem.name, MViewItem);
Vue.component(MEdit.name, MEdit);
Vue.component(MEditHint.name, MEditHint);
Vue.component(CodeEditor.name, CodeEditor);
Vue.component(JsonEditor.name, JsonEditor);
Vue.component(ColFormItem.name, ColFormItem);
Vue.component(SaveButton.name, SaveButton);
Vue.component(MDialog.name, MDialog);
Vue.component(MDrawer.name, MDrawer);
Vue.component(StateFilter.name, StateFilter);
Vue.component(DatetimeFilter.name, DatetimeFilter);
Vue.component(MCollapseItem.name, MCollapseItem);
Vue.component(MUploader.name, MUploader);
Vue.component(MPreviewer.name, MPreviewer);
Vue.component(MAddressView.name, MAddressView);
Vue.component(MAddressForm.name, MAddressForm);
Vue.component(MCommonSelect.name, MCommonSelect);
Vue.component(MAttachName.name, MAttachName);
Vue.component(MPortrait.name, MPortrait);
Vue.component(TreeChart.name, TreeChart);
Vue.component(TreeChartEmployee.name, TreeChartEmployee);
Vue.component(FlexItem.name, FlexItem);
Vue.component(Pagination.name, Pagination);
Vue.component(SimpleTable.name, SimpleTable);
Vue.component(PageTitle.name, PageTitle);
